### ISSUE TITLE
Python2.7 Travis failure

### ISSUE THREAD

**Issue by Zarad1993** [Zarad1993/dyc#47]
Dependency failure with python2.7 when installing pre-commit causing our build to fail.

<img width="856" alt="Screen Shot 2020-03-29 at 2 16 08 AM" src="https://user-images.githubusercontent.com/18662248/77835998-49ad0c00-7163-11ea-9dc0-89dc06efe8aa.png">

**Comment by Zarad1993** [comment]
Heads up @navyakanu

**Comment by navyakanu** [comment]
@Zarad1993 I am able to reproduce the issue in python 2.7 - just with the below command - 
                 `pip install -r requirements.txt`
The isssue is happening because of the requirement `gitpython==2.1.11` 
Removing this does not fail the installation of requirements.
The possible fix is to increase the dependency version to pick greater than 2.1.11 
`gitpython>=2.1.11`

**Comment by navyakanu** [comment]
#48

**Comment by Zarad1993** [comment]
Solved !
